export const APP_INIT = 'APP_INIT';

export const MOVIE_GET_ALL_PENDING = 'MOVIE_GET_ALL_PENDING';
export const MOVIE_GET_ALL_SUCCESS = 'MOVIE_GET_ALL_SUCCESS';
export const MOVIE_GET_ALL_ERROR = 'MOVIE_GET_ALL_ERROR';

export const MOVIE_ADD_NEW_PENDING = 'MOVIE_ADD_NEW_PENDING';
export const MOVIE_ADD_NEW_SUCCESS = 'MOVIE_ADD_NEW_SUCCESS';
export const MOVIE_ADD_NEW_ERROR = 'MOVIE_ADD_NEW_ERROR';

export const MOVIE_DELETE_PENDING = 'MOVIE_DELETE_PENDING';
export const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
export const MOVIE_DELETE_ERROR = 'MOVIE_DELETE_ERROR';

export const SEARCH_BY_NAME_PENDING = 'SEARCH_BY_NAME_PENDING';
export const SEARCH_BY_NAME_SUCCESS = 'SEARCH_BY_NAME_SUCCESS';
export const SEARCH_BY_NAME_ERROR = 'SEARCH_BY_NAME_ERROR';

export const SEARCH_BY_ACTOR_PENDING = 'SEARCH_BY_ACTOR_PENDING';
export const SEARCH_BY_ACTOR_SUCCESS = 'SEARCH_BY_ACTOR_SUCCESS';
export const SEARCH_BY_ACTOR_ERROR = 'SEARCH_BY_ACTOR_ERROR';

export const SORT_TITLE_DOWN = 'SORT_TITLE_DOWN';
export const SORT_TITLE_UP = 'SORT_TITLE_UP';
